---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hub-instance
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: openshift/core/operator/overlays/stable-2.3-cluster-scoped
    repoURL:  https://github.com/Red-Hat-SE-RTO/ocp4-ai-svc-universal-aap-configs.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
    - CreateNamespace=true