---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aap-install-config
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: openshift/core/apps/full-deployment
    repoURL: https://github.com/Red-Hat-SE-RTO/ocp4-ai-svc-universal-aap-configs.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true