---
controller_configuration_projects_async_retries: 120 # 120 * 5 = 600 seconds = 10 minutes
controller_projects_all:
  - name: ocp4-ai-svc-universal
    description: This set of resources handles an idempotent way to deploy OpenShift via the Assisted Installer Service to any number of infrastructure platforms.
    organization: ocp4-ai-svc-universal
    scm_type: git
    scm_url: https://github.com/Red-Hat-SE-RTO/ocp4-ai-svc-universal.git
    scm_branch: "{{ scm_branch }}"
    scm_clean: true
    scm_update_on_launch: false
    scm_credential: ""
    update_project: true
    wait: true
